### ISSUE TITLE
deleteIndieNotificationInbox not working

### ISSUE THREAD

**Issue by vishalpokuri** [NativeNotify/native-notify#11]
![image](https://github.com/user-attachments/assets/c4a1847a-78ad-4677-a4e6-f1c61d49f71f)

I thought its the problem with axios, so I tried to use fetch in the node modules, I guess the api point is not working.

**Comment by pagecow** [comment]
Please email your post details to support@nativenotify.com so we can run tests on our end. Everything is working on our end. I am closing this.
