### ISSUE TITLE
No experienceId or projectId found When Running Expo Dev Client

### ISSUE THREAD

**Issue by s3venvials** [NativeNotify/native-notify#2]
Hello when trying to use this library everything works locally with in expo go but after creating an APK build and installing the app on my device and running with npx expo start --dev-client it loads with the following error.

Error: "[Unhandled promise rejection: Error: No experienceId or projectId found. If one or the other can't be inferred from the manifest (eg. in bare workflow), you have to pass one in yourself.]"

Could not get it to work in my project so started with a brand new project to test it out and am still seeing the error.

Example Project: https://github.com/s3venvials/testnotify

According to the expo docs you would need to pass in the experienceId here.

`expoAndroidToken = (await Notifications.getExpoPushTokenAsync({ experienceId: "@username/projectSlug" })).data;`

Expo Docs: https://docs.expo.dev/versions/latest/sdk/notifications/

Any assistance is appreciated!

**Comment by NativeNotify** [comment]
Hi Mark,

There are a few extra steps to get Android push notifications working in
production (in an APK file). In the app documentation at NativeNotify.com,
there is an "Android" tab you can click on to see the Android production
setup instructions.

This video walks you through everything: https://youtu.be/dgXwABsAFxI

**Comment by s3venvials** [comment]
Hey thank you for your response! So I have followed your video and I finally got it to work but the main difference was that before I added my google-services.json file to my gitignore and was using expo eas secrets to set it the first time around. Also instead of a app.json I was using an app.config.js file so I could reference my google-services file from process.env per the expo docs. I would prefer not to have to push up my google-services file unless there is something else at play here. Just thought I would update you, not sure if that was taken into account.

One other issue is that when the app is closed I get the following warning below. Is that something I need to set up on my end?
"No task registered for key ReactNativeFirebaseMessagingHeadlessTask"

**Comment by NativeNotify** [comment]
Hi Mark. I'm glad you got it working! 

You don't have to worry about the Firebase warning. You can ignore it. I believe that function is related to the background listener listening for when a user taps a notification and doesn't perform any tasks until a user taps on a notification.

The app.json and and putting the google-service.json instructions are based on Expo's documentation. Expo says it needs to be set up this way in order to successfully get the push tokens within Expo managed workflow.
