### ISSUE TITLE
Error: Expected package @expo/config-plugins@~7.2.2 but found @expo/config-plugins@6.0.2

### ISSUE THREAD

**Issue by dmhfbkfhsdbhfdjkdybhvbfk** [NativeNotify/native-notify#3]
I encountered an issue while working on my Expo project. The error message I received is as follows:

`Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@6.0.2
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions.
` and when i ran npm why i got this.
`
@expo/config-plugins@6.0.2
node_modules/native-notify/node_modules/@expo/config-plugins
  @expo/config-plugins@"~6.0.0" from @expo/config@8.0.5
  node_modules/native-notify/node_modules/@expo/config
    @expo/config@"~8.0.0" from expo-constants@14.2.1
    node_modules/native-notify/node_modules/expo-constants
      expo-constants@"~14.2.0" from expo-notifications@0.18.1
      node_modules/native-notify/node_modules/expo-notifications
        expo-notifications@"~0.18.1" from native-notify@3.1.0
        node_modules/native-notify
          native-notify@"^3.1.0" from the root project `  
 and i installed your library to the latest but no way to resolve this

Expected Behavior: I expected the project to work with @expo/config-plugins version 7.2.2 as specified in my project configuration.
Actual Behavior: However, the project encountered an issue because it found @expo/config-plugins version 6.0.2 instead.

Expo version: 49.0.13
Node.js version: 18.17.0
npm version: 9.6.7

I'm seeking help in resolving this issue and understanding the root cause of the unexpected package version mismatch. Any guidance or suggestions would be greatly appreciated.

**Comment by pagecow** [comment]
This issue is not related to the native-notify package. Based on the error, maybe try to run this in your terminal 'npx expo install @expo/config-plugins@~7.2.2'.

That is just a guess. It looks like you need @expo/config-plugins@~7.2.2 installed based on the error.

**Comment by dmhfbkfhsdbhfdjkdybhvbfk** [comment]
thank you very much for this , your idea didn't fully remove the error but my code compiled successfully to `.aab` format using eas build

**Comment by hanif865** [comment]
but if install NativeNotify expo docor provide this error if remove NativeNotify no error or warning found

![Screenshot_391](https://github.com/NativeNotify/native-notify/assets/99798066/44205c3f-837b-4b9e-bac8-76c466eb003f)

**Comment by hanif865** [comment]
![Screenshot_392](https://github.com/NativeNotify/native-notify/assets/99798066/4534fca4-8297-41d5-9607-8dbdc39ad793)

**Comment by NativeNotify** [comment]
This issue has been resolved for native-notify version 3.2.7. Please upgrade to version 3.2.7 and the warning should go away.
