### ISSUE TITLE
⚠Update @expo/config-plugins

### ISSUE THREAD

**Issue by Lakshya7312** [NativeNotify/native-notify#4]
On running the `expo-doctor` command, I see the warning to update `@expo/config-plugins` to the latest supported
version which is `~7.2.2`

The current version used is shown as `6.0.2`

Please fix.

![image](https://github.com/NativeNotify/native-notify/assets/53973772/6ebba55d-ba03-4ab2-8eaa-6b841b9c6ae9)

**Comment by pagecow** [comment]
I think the error may be telling you to upgrade to @expo/config-plugins@7.2.2. That dependency is not part of the native-notify package. Here is a recent app I worked on's package.json dependencies:

`
    "@expo/config-plugins": "~7.2.2",
    "native-notify": "^3.2.4",
    ...
`

My app needed to have "@expo/config-plugins": "~7.2.2", but in the native-notify package, there was not an @expo/config-plugins dependency.

**Comment by Lakshya7312** [comment]
Hi, thanks for your response.
I've added the dependency but am facing another warning now:
![image](https://github.com/NativeNotify/native-notify/assets/53973772/02dadbd2-f57c-4770-a470-79c18af0b9e8)
Any ideas how to fix this?

**Comment by pagecow** [comment]
You can ignore that warning. You should still get the notifications.

This warning is thrown sometimes by Android. Some Android phones have their own internal push notification authorization checker. The native-notify package has a push notification authorization checker too. If an Android phone triggers its internal checker first before the native-notify package checker runs, this warning sometimes appears. But it is nothing to worry about. Everything should still work.

**Comment by Lakshya7312** [comment]
@pagecow 

i thought the same but my notifications still don't appear, I get an error in the native notify portal.

**Comment by pagecow** [comment]
You could email support@nativenotify.com for help.

**Comment by NativeNotify** [comment]
This issue has been resolved for native-notify version 3.2.7. Please upgrade to version 3.2.7 and the warning should go away.
