### ISSUE TITLE
not working in Expo build real device 

### ISSUE THREAD

**Issue by miteshdevg** [NativeNotify/native-notify#7]
native notify is not working in the expo build it's working fine while the app running in Expo go

**Comment by miteshdevg** [comment]
@pagecow 
can you please help me to solve issue

**Comment by pagecow** [comment]
If you look in the documentation, there is an "Android" page. You have to follow a few more steps to get push notifications working in Android Production mode. This video walks through all the steps: https://youtu.be/pQvl-NX9mW4?si=B_7oQcZvX4fD9THq

**Comment by miteshdevg** [comment]
i have followed it but it's not working ,

**Comment by miteshdevg** [comment]
I think I was confused about selecting google console json file

**Comment by miteshdevg** [comment]
@pagecow can you please help,

**Comment by pagecow** [comment]
Please follow the instructions in this video: https://youtu.be/o4BEghdLetc?si=zyJOT1kmm-2f8n8b
