### ISSUE TITLE
navigation when click on notification

### ISSUE THREAD

**Issue by miteshdevg** [NativeNotify/native-notify#8]
I can't navigate when I click on the notification I want to navigate 
can I navigate it 
Please give me a response @pagecow

**Comment by miteshdevg** [comment]
@pagecow are you there 

Please resolve issue

**Comment by pagecow** [comment]
You can use the Push Data Object feature to navigate to a specific page. We will be making a video tutorial explaining how to do this on our Native Notify YouTube channel within the next week or two.
