### ISSUE TITLE
Undefined responseListener Causes Crash on Notification Unsubscription

### ISSUE THREAD

**Issue by mazenashgar** [NativeNotify/native-notify#9]
### Environment Details:
Library Version: native-notify v4.0.4 
React Native Version: 0.75.4
Platform: Android

### Issue Description:
An error occurs when attempting to unsubscribe from notifications in the useEffect cleanup function. Specifically, the responseListener variable is undefined, leading to a crash when calling Notifications.removeNotificationSubscription(responseListener);. This error prevents the app from properly handling push notifications and affects Android only(as our Sentry has reported).

![Screenshot 2024-11-05 at 7 29 03 PM](https://github.com/user-attachments/assets/9a726fc4-21cb-4a11-b5ee-13082eac40ca)

**Comment by MAl-l3R** [comment]
I am getting the same error. App won't even start up when I npx expo start. I'm unable to use push notification from native notify.

**Comment by pagecow** [comment]
Please upgrade to native-notify version 4.0.5. We made some updates to get the package working with the new EAS build system by Expo. 

The Android documentation has also been updated within the past week. Please go into your NativeNotify.com app to make sure you are following the new documentation. 

Everything should be working properly.

**Comment by pagecow** [comment]
We discovered the bug reported and have fixed the bug for native-notify version 4.0.6. Please upgrade to version 4.0.6.
